name: Build Python .whl

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Build .whl
        run: |
          cd python
          python -m pip install --upgrade build
          python -m build
      - name: Store Output
        uses: actions/upload-artifact@v2
        with:
          name: logic2-automation-python
          path: python/dist/*.whl
    
